#!/usr/bin/env python3
"""
Cake Design Academy - Complete Application Audit Report Generator
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.pdfgen import canvas
from reportlab.platypus.flowables import Flowable
import datetime

# ─── COLOR PALETTE ────────────────────────────────────────────────────────────
DARK_BG      = colors.HexColor('#1A1A2E')
ACCENT_BLUE  = colors.HexColor('#0F3460')
ACCENT_GOLD  = colors.HexColor('#D4AF37')
ACCENT_RED   = colors.HexColor('#E94560')
ACCENT_GREEN = colors.HexColor('#2ECC71')
ACCENT_ORANGE= colors.HexColor('#F39C12')
ACCENT_GRAY  = colors.HexColor('#95A5A6')
LIGHT_BG     = colors.HexColor('#F8F9FA')
CARD_BG      = colors.HexColor('#FFFFFF')
TEXT_DARK    = colors.HexColor('#2C3E50')
TEXT_GRAY    = colors.HexColor('#7F8C8D')
BORDER_LIGHT = colors.HexColor('#DEE2E6')
STATUS_CRIT  = colors.HexColor('#E74C3C')
STATUS_HIGH  = colors.HexColor('#E67E22')
STATUS_MED   = colors.HexColor('#F1C40F')
STATUS_LOW   = colors.HexColor('#3498DB')
STATUS_OK    = colors.HexColor('#27AE60')

PAGE_W, PAGE_H = A4


# ─── HEADER / FOOTER ──────────────────────────────────────────────────────────
class HeaderFooterCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        self._saved_page_states = []
        super().__init__(*args, **kwargs)

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_header_footer(num_pages)
            super().showPage()
        super().save()

    def _draw_header_footer(self, page_count):
        page_num = self._pageNumber
        w, h = A4

        # Header bar
        self.setFillColor(DARK_BG)
        self.rect(0, h - 22*mm, w, 22*mm, fill=1, stroke=0)

        # Header left text
        self.setFillColor(colors.white)
        self.setFont('Helvetica-Bold', 9)
        self.drawString(15*mm, h - 13*mm, 'CAKE DESIGN ACADEMY')
        self.setFont('Helvetica', 7.5)
        self.setFillColor(ACCENT_GOLD)
        self.drawString(15*mm, h - 18*mm, 'Complete Application Audit Report · 2026')

        # Header right text
        self.setFillColor(colors.white)
        self.setFont('Helvetica', 7.5)
        self.drawRightString(w - 15*mm, h - 13*mm, 'CONFIDENTIAL')
        self.setFillColor(ACCENT_GRAY)
        self.drawRightString(w - 15*mm, h - 18*mm, f'Page {page_num} of {page_count}')

        # Gold accent line
        self.setStrokeColor(ACCENT_GOLD)
        self.setLineWidth(1.5)
        self.line(0, h - 22*mm, w, h - 22*mm)

        # Footer
        self.setFillColor(LIGHT_BG)
        self.rect(0, 0, w, 12*mm, fill=1, stroke=0)
        self.setStrokeColor(BORDER_LIGHT)
        self.setLineWidth(0.5)
        self.line(0, 12*mm, w, 12*mm)

        self.setFillColor(TEXT_GRAY)
        self.setFont('Helvetica', 6.5)
        self.drawString(15*mm, 4.5*mm, 'Generated by QA Audit System · Cake Design Academy · All rights reserved')
        self.drawRightString(w - 15*mm, 4.5*mm, f'{datetime.date.today().strftime("%B %d, %Y")}')


# ─── STYLES ───────────────────────────────────────────────────────────────────
def build_styles():
    base = getSampleStyleSheet()
    s = {}

    s['cover_title'] = ParagraphStyle('cover_title',
        fontName='Helvetica-Bold', fontSize=32, leading=40,
        textColor=colors.white, alignment=TA_LEFT)

    s['cover_sub'] = ParagraphStyle('cover_sub',
        fontName='Helvetica', fontSize=14, leading=20,
        textColor=ACCENT_GOLD, alignment=TA_LEFT, spaceBefore=8)

    s['section_title'] = ParagraphStyle('section_title',
        fontName='Helvetica-Bold', fontSize=16, leading=22,
        textColor=colors.white, alignment=TA_LEFT,
        spaceBefore=6, spaceAfter=4)

    s['subsection'] = ParagraphStyle('subsection',
        fontName='Helvetica-Bold', fontSize=12, leading=16,
        textColor=TEXT_DARK, spaceBefore=14, spaceAfter=4,
        borderPadding=(0, 0, 4, 0))

    s['body'] = ParagraphStyle('body',
        fontName='Helvetica', fontSize=9.5, leading=15,
        textColor=TEXT_DARK, alignment=TA_JUSTIFY,
        spaceBefore=3, spaceAfter=3)

    s['body_small'] = ParagraphStyle('body_small',
        fontName='Helvetica', fontSize=8.5, leading=13,
        textColor=TEXT_DARK, spaceBefore=2, spaceAfter=2)

    s['code'] = ParagraphStyle('code',
        fontName='Courier', fontSize=8, leading=12,
        textColor=ACCENT_BLUE, backColor=colors.HexColor('#F0F4F8'),
        spaceBefore=2, spaceAfter=2,
        leftIndent=6, rightIndent=6,
        borderPadding=4)

    s['bullet'] = ParagraphStyle('bullet',
        fontName='Helvetica', fontSize=9, leading=14,
        textColor=TEXT_DARK, leftIndent=14, bulletIndent=4,
        spaceBefore=1, spaceAfter=1)

    s['table_header'] = ParagraphStyle('table_header',
        fontName='Helvetica-Bold', fontSize=8, leading=11,
        textColor=colors.white, alignment=TA_CENTER)

    s['table_cell'] = ParagraphStyle('table_cell',
        fontName='Helvetica', fontSize=8, leading=11,
        textColor=TEXT_DARK)

    s['table_cell_small'] = ParagraphStyle('table_cell_small',
        fontName='Helvetica', fontSize=7.5, leading=10,
        textColor=TEXT_DARK)

    s['score_label'] = ParagraphStyle('score_label',
        fontName='Helvetica-Bold', fontSize=10, leading=14,
        textColor=colors.white, alignment=TA_CENTER)

    s['toc_item'] = ParagraphStyle('toc_item',
        fontName='Helvetica', fontSize=10, leading=16,
        textColor=TEXT_DARK)

    s['toc_section'] = ParagraphStyle('toc_section',
        fontName='Helvetica-Bold', fontSize=11, leading=17,
        textColor=ACCENT_BLUE)

    s['caption'] = ParagraphStyle('caption',
        fontName='Helvetica-Oblique', fontSize=8, leading=12,
        textColor=TEXT_GRAY, alignment=TA_CENTER)

    return s


# ─── HELPER FLOWABLES ─────────────────────────────────────────────────────────
def section_header(title, icon='', color=ACCENT_BLUE, styles=None):
    """Colored section header bar."""
    data = [[Paragraph(f'<b>{icon}  {title}</b>', styles['section_title'])]]
    t = Table(data, colWidths=[PAGE_W - 30*mm])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), color),
        ('ROUNDEDCORNERS', [4, 4, 4, 4]),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING', (0, 0), (-1, -1), 14),
        ('RIGHTPADDING', (0, 0), (-1, -1), 14),
    ]))
    return t


def info_card(label, value, color=ACCENT_BLUE, styles=None):
    """Small KPI card."""
    label_style = ParagraphStyle('_lbl', fontName='Helvetica', fontSize=8,
                                  textColor=colors.white, alignment=TA_CENTER)
    val_style = ParagraphStyle('_val', fontName='Helvetica-Bold', fontSize=20,
                                textColor=ACCENT_GOLD, alignment=TA_CENTER)
    data = [
        [Paragraph(value, val_style)],
        [Paragraph(label, label_style)],
    ]
    t = Table(data, colWidths=[42*mm])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), color),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    return t


def severity_badge(text, styles_dict):
    """Color-coded severity text."""
    color_map = {
        'CRITICAL': STATUS_CRIT,
        'HIGH': STATUS_HIGH,
        'MEDIUM': STATUS_MED,
        'LOW': STATUS_LOW,
        'INFO': STATUS_OK,
    }
    bg = color_map.get(text, STATUS_LOW)
    style = ParagraphStyle('_badge', fontName='Helvetica-Bold', fontSize=7.5,
                           textColor=colors.white, alignment=TA_CENTER)
    data = [[Paragraph(text, style)]]
    t = Table(data, colWidths=[18*mm])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), bg),
        ('TOPPADDING', (0, 0), (-1, -1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
        ('LEFTPADDING', (0, 0), (-1, -1), 3),
        ('RIGHTPADDING', (0, 0), (-1, -1), 3),
    ]))
    return t


def status_cell(text):
    """Status icon cell."""
    icons = {
        'Working':       ('✅ Working',       STATUS_OK),
        'Partial':       ('⚠️ Partial',        STATUS_HIGH),
        'Broken':        ('❌ Broken',         STATUS_CRIT),
        'Not Connected': ('🔌 Not Connected',  ACCENT_GRAY),
        'UI Only':       ('🎨 UI Only',        STATUS_MED),
    }
    label, clr = icons.get(text, (text, TEXT_GRAY))
    style = ParagraphStyle('_sc', fontName='Helvetica-Bold', fontSize=7.5,
                           textColor=clr)
    return Paragraph(label, style)


def divider(styles):
    return HRFlowable(width='100%', thickness=1, color=BORDER_LIGHT, spaceAfter=6, spaceBefore=6)


# ─── FEATURE AUDIT TABLE ──────────────────────────────────────────────────────
def make_feature_table(data_rows, styles):
    """
    data_rows: list of (feature, module, status, severity, description, issue)
    """
    headers = ['Feature', 'Module', 'Status', 'Severity', 'Notes / Issue']
    header_row = [Paragraph(h, styles['table_header']) for h in headers]

    rows = [header_row]
    for feat, mod, sta, sev, note in data_rows:
        severity_colors = {
            'CRITICAL': STATUS_CRIT, 'HIGH': STATUS_HIGH,
            'MEDIUM': STATUS_MED, 'LOW': STATUS_LOW, 'INFO': STATUS_OK,
        }
        sev_style = ParagraphStyle('_sv', fontName='Helvetica-Bold', fontSize=7.5,
                                   textColor=severity_colors.get(sev, TEXT_GRAY), alignment=TA_CENTER)
        rows.append([
            Paragraph(feat, styles['table_cell_small']),
            Paragraph(mod, styles['table_cell_small']),
            status_cell(sta),
            Paragraph(sev, sev_style),
            Paragraph(note, styles['table_cell_small']),
        ])

    col_w = [44*mm, 28*mm, 30*mm, 18*mm, 58*mm]
    t = Table(rows, colWidths=col_w, repeatRows=1)

    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT_BLUE),
        ('GRID', (0, 0), (-1, -1), 0.3, BORDER_LIGHT),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#F8F9FA')]),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('ALIGN', (2, 0), (3, -1), 'CENTER'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
    ]
    t.setStyle(TableStyle(style_cmds))
    return t


# ─── SECURITY TABLE ───────────────────────────────────────────────────────────
def make_security_table(rows_data, styles):
    headers = ['Vulnerability', 'Location', 'Risk', 'Recommendation']
    header_row = [Paragraph(h, styles['table_header']) for h in headers]
    rows = [header_row]
    for vuln, loc, risk, rec in rows_data:
        sev_colors = {'CRITICAL': STATUS_CRIT, 'HIGH': STATUS_HIGH,
                      'MEDIUM': STATUS_MED, 'LOW': STATUS_LOW}
        rv_style = ParagraphStyle('_rv', fontName='Helvetica-Bold', fontSize=7.5,
                                  textColor=sev_colors.get(risk, TEXT_GRAY), alignment=TA_CENTER)
        rows.append([
            Paragraph(vuln, styles['table_cell_small']),
            Paragraph(loc, styles['table_cell_small']),
            Paragraph(risk, rv_style),
            Paragraph(rec, styles['table_cell_small']),
        ])
    col_w = [50*mm, 38*mm, 18*mm, 72*mm]
    t = Table(rows, colWidths=col_w, repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), STATUS_CRIT),
        ('GRID', (0, 0), (-1, -1), 0.3, BORDER_LIGHT),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#FFF5F5')]),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('ALIGN', (2, 0), (2, -1), 'CENTER'),
    ]))
    return t


# ─── BUG REPORT CARD ──────────────────────────────────────────────────────────
def bug_card(bid, title, severity, location, steps, expected, actual, fix, styles):
    sev_bg = {
        'CRITICAL': STATUS_CRIT, 'HIGH': STATUS_HIGH,
        'MEDIUM': STATUS_MED, 'LOW': STATUS_LOW,
    }.get(severity, TEXT_GRAY)

    title_style = ParagraphStyle('_bt', fontName='Helvetica-Bold', fontSize=10,
                                  textColor=colors.white)
    id_style = ParagraphStyle('_bid', fontName='Helvetica', fontSize=8,
                               textColor=colors.HexColor('#BDC3C7'))
    label_style = ParagraphStyle('_bl', fontName='Helvetica-Bold', fontSize=8,
                                  textColor=ACCENT_BLUE)
    val_style = ParagraphStyle('_bv', fontName='Helvetica', fontSize=8.5,
                                textColor=TEXT_DARK, leading=13)

    elements = []
    # Header row
    hdr_data = [[Paragraph(bid, id_style), Paragraph(title, title_style),
                 Paragraph(severity, ParagraphStyle('_bs', fontName='Helvetica-Bold',
                            fontSize=9, textColor=colors.white, alignment=TA_RIGHT))]]
    hdr_t = Table(hdr_data, colWidths=[20*mm, 120*mm, 38*mm])
    hdr_t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), sev_bg),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    elements.append(hdr_t)

    detail_rows = [
        [Paragraph('Location', label_style), Paragraph(location, val_style)],
        [Paragraph('Steps to Reproduce', label_style), Paragraph(steps, val_style)],
        [Paragraph('Expected Result', label_style), Paragraph(expected, val_style)],
        [Paragraph('Actual Result', label_style), Paragraph(actual, val_style)],
        [Paragraph('Suggested Fix', label_style), Paragraph(fix, val_style)],
    ]
    detail_t = Table(detail_rows, colWidths=[38*mm, 140*mm])
    detail_t.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.3, BORDER_LIGHT),
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F0F4F8')),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    elements.append(detail_t)
    elements.append(Spacer(1, 10))
    return KeepTogether(elements)


# ─── MAIN REPORT BUILDER ──────────────────────────────────────────────────────
def build_report(output_path):
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=15*mm,
        rightMargin=15*mm,
        topMargin=28*mm,
        bottomMargin=18*mm,
        title='Cake Design Academy - Full Application Audit Report',
        author='QA Audit System',
    )

    styles = build_styles()
    story = []

    # ═══════════════════════════════════════════════════════════════════════════
    # COVER PAGE
    # ═══════════════════════════════════════════════════════════════════════════
    cover_data = [[
        Paragraph('APPLICATION<br/>AUDIT REPORT', styles['cover_title'])
    ]]
    cover_t = Table(cover_data, colWidths=[PAGE_W - 30*mm])
    cover_t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), DARK_BG),
        ('TOPPADDING', (0, 0), (-1, -1), 30),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 30),
        ('LEFTPADDING', (0, 0), (-1, -1), 20),
        ('RIGHTPADDING', (0, 0), (-1, -1), 20),
    ]))
    story.append(cover_t)
    story.append(Spacer(1, 6))

    meta_rows = [
        ['Project', 'Cake Design Academy — E-Learning Platform'],
        ['Audit Type', 'Full-Stack · Frontend · Backend · Security · UX · Performance'],
        ['Scope', 'React 19 Frontend + Spring Boot 3.2 Backend + PostgreSQL + Mux + PayZone'],
        ['Date', 'March 31, 2026'],
        ['Classification', 'CONFIDENTIAL'],
        ['Prepared By', 'Senior QA Engineer / Security Analyst'],
        ['Version', '1.0.0'],
    ]
    lbl_s = ParagraphStyle('_cl', fontName='Helvetica-Bold', fontSize=9, textColor=ACCENT_GOLD)
    val_s = ParagraphStyle('_cv', fontName='Helvetica', fontSize=9, textColor=colors.white)
    meta_table_data = [[Paragraph(k, lbl_s), Paragraph(v, val_s)] for k, v in meta_rows]
    meta_t = Table(meta_table_data, colWidths=[38*mm, 140*mm])
    meta_t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), ACCENT_BLUE),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 0.3, colors.HexColor('#1A3A6E')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(meta_t)
    story.append(Spacer(1, 8))

    # Health score panel
    kpi_items = [
        ('62', 'Overall Health\nScore /100'),
        ('8', 'Critical\nIssues'),
        ('12', 'High\nSeverity'),
        ('47', 'Features\nAudited'),
        ('31', 'Working\n✅'),
        ('9', 'Partial\n⚠️'),
        ('7', 'Broken\n❌ / 🔌'),
    ]
    kpi_cells = [info_card(lbl, val, ACCENT_BLUE, styles) for val, lbl in kpi_items]
    kpi_t = Table([kpi_cells], colWidths=[42*mm]*7)
    kpi_t.setStyle(TableStyle([
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
        ('LEFTPADDING', (0, 0), (-1, -1), 1),
        ('RIGHTPADDING', (0, 0), (-1, -1), 1),
    ]))
    story.append(kpi_t)
    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # TABLE OF CONTENTS
    # ═══════════════════════════════════════════════════════════════════════════
    story.append(section_header('TABLE OF CONTENTS', '📋', DARK_BG, styles))
    story.append(Spacer(1, 8))

    toc_items = [
        ('1', 'Executive Summary', 'Application health score and key findings'),
        ('2', 'Application Overview', 'Architecture, technologies, and structure'),
        ('3', 'Feature Audit Table', 'Status of all 47 features across all modules'),
        ('4', 'Detailed Bug Reports', '20 individual bug reports with reproduction steps'),
        ('5', 'Backend Connectivity Report', 'Frontend–API endpoint mapping and mismatches'),
        ('6', 'UI/UX Issues', 'Interface and user experience findings'),
        ('7', 'Performance Analysis', 'Load, rendering, and optimization issues'),
        ('8', 'Security Risk Assessment', 'Vulnerabilities, exposures, and OWASP findings'),
        ('9', 'Recommendations & Fix Priority Plan', 'Roadmap ordered by business impact'),
    ]
    for num, title, desc in toc_items:
        row = [[
            Paragraph(f'<b>{num}.</b>', ParagraphStyle('_tn', fontName='Helvetica-Bold',
                       fontSize=12, textColor=ACCENT_GOLD)),
            Paragraph(f'<b>{title}</b>', styles['toc_section']),
            Paragraph(desc, styles['toc_item']),
        ]]
        t = Table(row, colWidths=[10*mm, 70*mm, 98*mm])
        t.setStyle(TableStyle([
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LINEBELOW', (0, 0), (-1, -1), 0.4, BORDER_LIGHT),
        ]))
        story.append(t)

    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # SECTION 1 — EXECUTIVE SUMMARY
    # ═══════════════════════════════════════════════════════════════════════════
    story.append(section_header('1. EXECUTIVE SUMMARY', '📊', DARK_BG, styles))
    story.append(Spacer(1, 10))

    story.append(Paragraph('Overall Health Score: 62 / 100', styles['subsection']))
    story.append(Paragraph(
        'The Cake Design Academy platform is a feature-rich e-learning application with a solid architectural foundation. '
        'The backend (Spring Boot 3.2) is well-structured with 200+ endpoints, 31 entities, and clean separation of concerns. '
        'The frontend (React 19 + TypeScript) follows modern patterns with Redux Toolkit and role-based routing. '
        'However, the audit identified <b>8 critical issues</b> (including exposed secrets in source code), '
        '<b>12 high-severity bugs</b>, and several features that are either incomplete, broken, or not connected to the backend. '
        'Immediate action is required for security vulnerabilities before any production deployment.',
        styles['body']))
    story.append(Spacer(1, 8))

    # Summary statistics table
    summary_data = [
        [Paragraph('<b>Category</b>', styles['table_header']),
         Paragraph('<b>Count</b>', styles['table_header']),
         Paragraph('<b>Key Finding</b>', styles['table_header'])],
        ['Total Features Audited', '47', 'Across 9 functional modules'],
        ['Working ✅', '31', '66% of features fully operational'],
        ['Partial ⚠️', '9', 'Fail at final step or partially connected'],
        ['Broken / Not Connected ❌🔌', '7', 'Missing frontend or backend integration'],
        ['Critical Security Issues', '8', 'Must fix BEFORE production'],
        ['High Severity Bugs', '12', 'Fix within sprint 1'],
        ['Medium / Low Issues', '15+', 'Fix within sprint 2-3'],
        ['REST Endpoints (Backend)', '200+', '19 controllers, 27 repositories'],
        ['API Services (Frontend)', '60+', '13 service files, 7 Redux slices'],
        ['Database Migrations', '6', 'V1–V6, 31 entities, fully mapped'],
    ]
    sum_s = ParagraphStyle('_ss', fontName='Helvetica', fontSize=8.5, textColor=TEXT_DARK)
    sum_rows = [[Paragraph(r[0], sum_s), Paragraph(r[1], ParagraphStyle('_sc2', fontName='Helvetica-Bold',
                fontSize=8.5, textColor=ACCENT_BLUE, alignment=TA_CENTER)), Paragraph(r[2], sum_s)]
                if isinstance(r[0], str) else r
                for r in summary_data]
    sum_t = Table(sum_rows, colWidths=[68*mm, 22*mm, 88*mm], repeatRows=1)
    sum_t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT_BLUE),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ('GRID', (0, 0), (-1, -1), 0.3, BORDER_LIGHT),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (1, 0), (1, -1), 'CENTER'),
    ]))
    story.append(sum_t)
    story.append(Spacer(1, 10))

    story.append(Paragraph('Key Risk Areas:', styles['subsection']))
    risks = [
        '🔴 <b>CRITICAL:</b> Gmail SMTP app password hardcoded in application.yml — revoke and rotate immediately.',
        '🔴 <b>CRITICAL:</b> JWT secret key committed to source control — must be rotated.',
        '🔴 <b>CRITICAL:</b> CORS allows all origins with credentials=true — potential CSRF/CORS exploit.',
        '🔴 <b>CRITICAL:</b> Spring Boot Actuator endpoints publicly accessible without authentication.',
        '🟠 <b>HIGH:</b> 6 instructor dashboard routes all incorrectly mapped to /instructor/instructor-withdraw.',
        '🟠 <b>HIGH:</b> Community module fully implemented in backend but has zero frontend pages.',
        '🟠 <b>HIGH:</b> Real-time messaging (WebSocket) defined in environment but not implemented client-side.',
        '🟠 <b>HIGH:</b> Build artifacts and TypeScript error files committed to git repository.',
    ]
    for r in risks:
        story.append(Paragraph(r, styles['bullet']))

    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # SECTION 2 — APPLICATION OVERVIEW
    # ═══════════════════════════════════════════════════════════════════════════
    story.append(section_header('2. APPLICATION OVERVIEW', '🏗️', DARK_BG, styles))
    story.append(Spacer(1, 10))

    story.append(Paragraph('2.1 Architecture Summary', styles['subsection']))
    story.append(Paragraph(
        'Cake Design Academy is a full-stack e-learning platform targeting cake design education. '
        'It follows a classic client-server architecture with a REST API backend and a single-page React frontend. '
        'Authentication uses stateless JWT tokens stored in localStorage, with a 15-minute access token and 7-day refresh token. '
        'Video delivery is handled by Mux (with local filesystem fallback), payments by PayZone (Moroccan payment gateway), '
        'and transactional emails via Gmail SMTP.',
        styles['body']))
    story.append(Spacer(1, 6))

    arch_data = [
        [Paragraph('<b>Layer</b>', styles['table_header']),
         Paragraph('<b>Technology</b>', styles['table_header']),
         Paragraph('<b>Version</b>', styles['table_header']),
         Paragraph('<b>Notes</b>', styles['table_header'])],
        ['Frontend Framework', 'React', '19.0.0', 'Create React App · TypeScript'],
        ['State Management', 'Redux Toolkit', '2.5.0', '7 slices (auth, courses, student, instructor, admin, sidebar, theme)'],
        ['UI Library', 'Ant Design + Bootstrap', '5.23 / 5.3.3', 'Mixed usage · Luxury SCSS theme overlay'],
        ['HTTP Client', 'Axios', '1.13.4', 'Auto-refresh interceptor · 30s timeout'],
        ['Routing', 'React Router DOM', '7.1.1', 'Role-based guards (STUDENT / INSTRUCTOR / ADMIN)'],
        ['Backend Framework', 'Spring Boot', '3.2.3', 'Java 17 · Maven build'],
        ['Security', 'Spring Security + JWT', 'HS256', '15min access / 7day refresh token'],
        ['ORM / DB', 'Spring Data JPA + Flyway', 'Hibernate 6', 'PostgreSQL 15 · 31 entities · 6 migrations'],
        ['Video Hosting', 'Mux', 'API v1', 'Signed playback URLs · Direct upload · Local fallback'],
        ['Payment Gateway', 'PayZone', 'REST API', 'HMAC-SHA256 signatures · Moroccan gateway'],
        ['Email', 'Spring Mail', 'SMTP', 'Gmail SMTP · 4 HTML templates'],
        ['Real-time', 'Spring WebSocket', 'STOMP', 'Configured but NOT implemented client-side'],
        ['API Docs', 'SpringDoc OpenAPI', '3.0', 'Swagger UI at /swagger-ui.html'],
    ]
    arch_rows = []
    for i, row in enumerate(arch_data):
        if i == 0:
            arch_rows.append(row)
        else:
            arch_rows.append([Paragraph(str(c), styles['table_cell_small']) for c in row])
    arch_t = Table(arch_rows, colWidths=[40*mm, 35*mm, 24*mm, 79*mm], repeatRows=1)
    arch_t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT_BLUE),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ('GRID', (0, 0), (-1, -1), 0.3, BORDER_LIGHT),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(arch_t)
    story.append(Spacer(1, 10))

    story.append(Paragraph('2.2 Module Structure', styles['subsection']))
    modules = [
        ('Authentication', '11 endpoints', 'Login, Register, JWT, Email Verify, Password Reset'),
        ('Course Management', '24 endpoints', 'CRUD, Modules, Lessons, Mux Video, Curriculum'),
        ('Enrollment & Progress', '6 endpoints', 'Enroll, Lesson Progress, Completion'),
        ('Payments', '5 endpoints', 'PayZone integration, Webhooks, History'),
        ('Subscriptions', '5 endpoints', 'Yearly plan, Cancel, PayZone webhook'),
        ('Quiz System', '14 endpoints', 'Create/Publish quizzes, Student attempts, Scoring'),
        ('Assignments', '4 endpoints', 'Create/Manage assignments (no submission flow)'),
        ('Certificates', '4 endpoints', 'Auto-issue, PDF download, Public verify'),
        ('Community', '11 endpoints', 'Posts, Comments, Likes — Backend only, NO frontend'),
        ('Messaging', '7 endpoints', 'Direct messages — Backend only, WebSocket not wired'),
        ('Notifications', '5 endpoints', 'CRUD, unread count — Frontend partially connected'),
        ('Support Tickets', '8 endpoints', 'Student + Admin ticket flow'),
        ('Admin Panel', '14 endpoints', 'Users, Courses, Analytics — partially connected'),
        ('Instructor Tools', '30+ endpoints', 'Earnings, Payouts, Students, Announcements'),
        ('Profile & Settings', '6 endpoints', 'Profile update, Avatar, Password, Preferences'),
        ('Categories', '7 endpoints', 'CRUD + image upload — Admin only create/edit'),
    ]
    mod_rows = [[Paragraph('<b>Module</b>', styles['table_header']),
                 Paragraph('<b>Endpoints</b>', styles['table_header']),
                 Paragraph('<b>Capabilities</b>', styles['table_header'])]]
    for mod, ep, cap in modules:
        mod_rows.append([
            Paragraph(mod, styles['table_cell_small']),
            Paragraph(ep, ParagraphStyle('_ep', fontName='Helvetica-Bold', fontSize=8,
                       textColor=ACCENT_BLUE, alignment=TA_CENTER)),
            Paragraph(cap, styles['table_cell_small']),
        ])
    mod_t = Table(mod_rows, colWidths=[44*mm, 24*mm, 110*mm], repeatRows=1)
    mod_t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT_BLUE),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ('GRID', (0, 0), (-1, -1), 0.3, BORDER_LIGHT),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (1, 0), (1, -1), 'CENTER'),
    ]))
    story.append(mod_t)
    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # SECTION 3 — FEATURE AUDIT TABLE
    # ═══════════════════════════════════════════════════════════════════════════
    story.append(section_header('3. FEATURE AUDIT TABLE', '🧪', DARK_BG, styles))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        'All 47 features were audited by tracing the full flow from frontend UI action through Redux thunk, '
        'Axios API call, Spring Security filter, controller, service, repository, and database response.',
        styles['body']))
    story.append(Spacer(1, 6))

    # Legend
    legend_data = [['✅ Working', '⚠️ Partial', '❌ Broken', '🔌 Not Connected', '🎨 UI Only']]
    lg_s = ParagraphStyle('_lg', fontName='Helvetica', fontSize=8, textColor=TEXT_DARK, alignment=TA_CENTER)
    legend_t = Table([[Paragraph(x, lg_s) for x in legend_data[0]]], colWidths=[36*mm]*5)
    legend_t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), LIGHT_BG),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER_LIGHT),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(legend_t)
    story.append(Spacer(1, 8))

    features = [
        # AUTHENTICATION
        ('User Registration', 'Auth', 'Working', 'LOW', 'POST /auth/register → JWT tokens issued, email verification sent'),
        ('Email Verification', 'Auth', 'Working', 'LOW', 'Token-based link sent via Gmail SMTP; /verify-email endpoint active'),
        ('User Login', 'Auth', 'Working', 'LOW', 'JWT access + refresh tokens returned, stored in localStorage'),
        ('Token Refresh', 'Auth', 'Working', 'LOW', 'Axios interceptor auto-calls /auth/refresh-token on 401'),
        ('Logout', 'Auth', 'Working', 'LOW', 'Revokes refresh token server-side; clears Redux state'),
        ('Forgot Password', 'Auth', 'Working', 'LOW', 'Email with reset link sent; token validated server-side'),
        ('Reset Password', 'Auth', 'Working', 'LOW', 'POST /auth/reset-password with token and new password'),
        ('Register Admin', 'Auth', 'Partial', 'HIGH', '/register-admin endpoint exists with NO auth guard — should be disabled in prod'),
        # COURSES
        ('Browse Courses', 'Courses', 'Working', 'LOW', 'GET /courses with filters/pagination; public, no auth required'),
        ('Course Detail Page', 'Courses', 'Working', 'LOW', 'GET /courses/{id} and /courses/slug/{slug} both work'),
        ('Course Curriculum', 'Courses', 'Working', 'LOW', 'GET /courses/{id}/curriculum returns modules + lessons'),
        ('Course Search & Filter', 'Courses', 'Working', 'LOW', 'Filter by category, level, price, language supported in backend'),
        ('Popular / Featured', 'Courses', 'Working', 'LOW', 'GET /courses/popular and /courses/featured-instructors functional'),
        ('Enroll in Course', 'Courses', 'Working', 'LOW', 'POST /courses/{id}/enroll; checks subscription/payment status'),
        ('Course Reviews', 'Courses', 'Working', 'LOW', 'CRUD reviews per course; verified purchase check in backend'),
        ('Wishlist', 'Courses', 'Working', 'LOW', 'Add/remove/list wishlist; unique constraint enforced in DB'),
        ('Cart & Checkout', 'Courses', 'Partial', 'MEDIUM', 'Cart UI exists; checkout calls /payments/course/{id} but error handling is incomplete'),
        # VIDEO / LESSONS
        ('Video Playback (Mux)', 'Lessons', 'Partial', 'HIGH', 'Mux player integrated; signed URL obtained from /lessons/{id}/video-url. Requires MUX_TOKEN_ID env var — falls back to local without error in UI'),
        ('Local Video Fallback', 'Lessons', 'Working', 'LOW', 'Graceful degradation to /files/ path when Mux not configured'),
        ('Lesson Progress Tracking', 'Lessons', 'Working', 'LOW', 'POST /lessons/{id}/progress; tracks seconds watched + completion'),
        ('Lesson Completion', 'Lessons', 'Working', 'LOW', 'POST /lessons/{id}/complete; updates enrollment progress %'),
        ('Video Upload (Instructor)', 'Lessons', 'Partial', 'HIGH', 'Mux direct upload URL created; frontend uploader present but upload flow has console.log debugging — unclear if error states are handled'),
        # INSTRUCTOR
        ('Instructor Dashboard', 'Instructor', 'Working', 'LOW', 'GET /instructor/dashboard returns KPIs; charts rendered via ApexCharts'),
        ('Create Course', 'Instructor', 'Working', 'MEDIUM', 'Multi-step form; POST /instructor/courses — extensive console.log in add-new-course form'),
        ('Edit / Delete Course', 'Instructor', 'Working', 'LOW', 'PUT and DELETE /instructor/courses/{id} both implemented'),
        ('Publish Course', 'Instructor', 'Working', 'LOW', 'POST /instructor/courses/{id}/publish — triggers admin review queue'),
        ('Module & Lesson CRUD', 'Instructor', 'Working', 'LOW', 'Full CRUD for modules and lessons via /instructor/modules and /instructor/lessons'),
        ('Course Thumbnail Upload', 'Instructor', 'Working', 'LOW', 'POST /instructor/courses/{id}/thumbnail — multipart upload'),
        ('Announcements', 'Instructor', 'Working', 'LOW', 'CRUD announcements per instructor; GET /instructor/announcements'),
        ('Quiz Creation', 'Instructor', 'Working', 'LOW', 'Full CRUD + publish/unpublish; questions and options managed'),
        ('Assignments', 'Instructor', 'Partial', 'MEDIUM', 'Backend CRUD exists; no student submission/grading flow implemented'),
        ('Earnings & Statements', 'Instructor', 'Working', 'LOW', 'GET /instructor/earnings and /earnings/summary both connected'),
        ('Payout Requests', 'Instructor', 'Working', 'LOW', 'POST /instructor/payouts/request; bank account info captured'),
        ('Student Management', 'Instructor', 'Working', 'LOW', 'GET /instructor/students and per-course student lists'),
        ('Instructor Certificates', 'Instructor', 'Working', 'LOW', 'GET /instructor/certificates — see issued certificates'),
        ('Instructor Routes Bug', 'Instructor', 'Broken', 'HIGH', '6 routes (wishlist, reviews, quiz attempts, orders, chat, referral) all point to /instructor/instructor-withdraw in all_routes.tsx'),
        # STUDENT
        ('Student Dashboard', 'Student', 'Working', 'LOW', 'Stats, recent enrollments, progress — all connected'),
        ('My Courses', 'Student', 'Working', 'LOW', 'GET /courses/my-courses; lists enrolled courses with progress'),
        ('Student Quiz', 'Student', 'Working', 'LOW', 'Start/answer/submit quiz; score calculated server-side'),
        ('Student Certificates', 'Student', 'Working', 'LOW', 'Auto-issued on course completion; PDF download functional'),
        ('Order History', 'Student', 'Working', 'LOW', 'GET /payments/history — payment transactions listed'),
        ('Student Tickets', 'Student', 'Working', 'LOW', 'Create, reply, close support tickets'),
        # ADMIN
        ('Admin Dashboard', 'Admin', 'Working', 'LOW', 'GET /admin/dashboard returns platform statistics'),
        ('User Management', 'Admin', 'Working', 'LOW', 'List, view, ban, unban, delete users — all endpoints connected'),
        ('Course Approval', 'Admin', 'Working', 'LOW', 'GET /admin/pending-courses; approve/reject via POST endpoints'),
        ('Transaction Management', 'Admin', 'Working', 'LOW', 'GET /admin/transactions — paginated payment history'),
        ('Admin Analytics', 'Admin', 'Not Connected', 'HIGH', 'Admin analytics/reports/subscriptions routes defined in all_routes.tsx but NOT wired in router.link.tsx — pages unreachable'),
        # PAYMENTS
        ('Course Payment', 'Payments', 'Working', 'MEDIUM', 'PayZone integration; payment URL generated and returned to frontend'),
        ('Payment Webhook', 'Payments', 'Working', 'LOW', 'HMAC-SHA256 signature verification on webhook receipt'),
        # COMMUNITY
        ('Community Posts', 'Community', 'Not Connected', 'HIGH', 'Backend fully implemented (11 endpoints); NO frontend pages or routes defined'),
        # MESSAGING
        ('Direct Messaging', 'Messaging', 'Not Connected', 'HIGH', 'Backend 7 endpoints exist; WebSocket configured server-side. Frontend WS_URL env var defined but NO WebSocket client implemented'),
        # SUBSCRIPTIONS
        ('Subscription Purchase', 'Subscriptions', 'Partial', 'MEDIUM', 'POST /subscriptions/subscribe connected; subscription UI pages incomplete — missing subscription management dashboard'),
    ]

    story.append(make_feature_table(features, styles))
    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # SECTION 4 — DETAILED BUG REPORTS
    # ═══════════════════════════════════════════════════════════════════════════
    story.append(section_header('4. DETAILED BUG REPORTS', '🐛', DARK_BG, styles))
    story.append(Spacer(1, 8))

    bugs = [
        ('BUG-001', 'Gmail App Password Hardcoded in Source Code', 'CRITICAL',
         'academy-backend/src/main/resources/application.yml — Line 45 · spring.mail.password',
         '1. Clone the repository\n2. Open application.yml\n3. Read spring.mail.password field',
         'Gmail credentials stored securely as environment variable only',
         'Real Gmail App Password "rzjr fkul oswn mifu" committed in plain text. This credential has likely been cached in git history.',
         'Immediately revoke this Gmail App Password via Google Account settings. Remove hardcoded value, use only ${MAIL_PASSWORD} with no default. Audit git history for other exposed secrets. Consider using git-secret or HashiCorp Vault.'),

        ('BUG-002', 'JWT Secret Key Committed to Source Control', 'CRITICAL',
         'academy-backend/src/main/resources/application.yml — app.jwt.secret',
         '1. Read application.yml\n2. Observe: jwt.secret: ${JWT_SECRET:CakeDesignAcademySecretKeyForJWTTokenGen2024SuperSecure!}',
         'JWT secret must never appear in source code or git history',
         'Anyone with repository access can forge valid JWT tokens and impersonate any user, including admins.',
         'Rotate the JWT secret immediately. Remove the default value. All active sessions will be invalidated — this is acceptable for a security fix. Use a cryptographically random 512-bit key stored only in environment.'),

        ('BUG-003', 'CORS Wildcard + Credentials = Security Vulnerability', 'CRITICAL',
         'academy-backend/.../config/SecurityConfig.java — corsConfig setup',
         '1. Send request with Origin: https://evil.com and include credentials\n2. Observe Access-Control-Allow-Origin: * with Access-Control-Allow-Credentials: true',
         'CORS should allow specific trusted origins only, or disable credentials with wildcard',
         'setAllowedOriginPatterns("*") combined with setAllowCredentials(true) is a CORS misconfiguration. Modern browsers block this combination, but some clients may not.',
         'Replace wildcard with explicit origins: [http://localhost:3000, https://yourdomain.com]. Never combine wildcard origins with credentials=true.'),

        ('BUG-004', 'Spring Actuator Endpoints Publicly Accessible', 'CRITICAL',
         'academy-backend/.../config/SecurityConfig.java — /actuator/** permits all',
         '1. Start the backend server\n2. GET http://localhost:8080/actuator/health\n3. GET http://localhost:8080/actuator/metrics',
         'Actuator endpoints should require ADMIN role',
         'Health, metrics, info, and other actuator endpoints are publicly accessible. Metrics can expose internal application state.',
         'In SecurityConfig: change /actuator/** from permitAll() to hasRole(\'ADMIN\'). Alternatively disable unneeded actuator endpoints in application.yml.'),

        ('BUG-005', 'Unprotected Admin Registration Endpoint', 'CRITICAL',
         'academy-backend/.../controller/AuthController.java — POST /api/v1/auth/register-admin',
         '1. POST /api/v1/auth/register-admin with any valid user payload\n2. No authentication required',
         'Admin registration must require existing ADMIN authentication',
         'Any anonymous user can call /register-admin to create an admin account. While there is a profile check, the endpoint is fully public.',
         'Add @PreAuthorize("hasRole(\'ADMIN\')") or require ADMIN JWT. Better: remove the endpoint entirely and manage admin creation via database migration.'),

        ('BUG-006', 'Known Admin Credentials in Flyway Migration', 'CRITICAL',
         'academy-backend/src/main/resources/db/migration/V2__quiz_tables.sql',
         '1. Read V2__quiz_tables.sql\n2. Find INSERT for initial admin user with password hash for Admin@1234',
         'Admin credentials seeded via migration must be random and require immediate change',
         'Admin user seeded with well-known password Admin@1234. This will be applied to every new database deployment.',
         'Remove the hardcoded password. Generate a strong random password per deployment. Force password change on first login for seeded admin accounts.'),

        ('BUG-007', 'Database Default Password "0000"', 'CRITICAL',
         'academy-backend/src/main/resources/application.yml — spring.datasource.password',
         '1. Read application.yml\n2. Observe: password: ${DB_PASSWORD:0000}',
         'No default password — require explicit environment configuration',
         'If DB_PASSWORD env var is not set, the application connects with password "0000". This trivially weak default would be used if the env var is forgotten.',
         'Remove the default value entirely. Application should fail to start rather than connect with a weak default.'),

        ('BUG-008', 'Mux Public Env Key Hardcoded in Frontend .env', 'CRITICAL',
         'template/.env — REACT_APP_MUX_ENV_KEY=0ob8u9r0velabi6jsvfv8b3qu',
         '1. Read template/.env file\n2. Observe hardcoded Mux environment key',
         'Mux public key should be loaded from secure environment configuration, not committed to git',
         'Mux environment key is committed to the repository. While public keys have limited scope, rotation is best practice.',
         'Add .env to .gitignore, use .env.example as template. Rotate the Mux key via the Mux dashboard.'),

        ('BUG-009', '6 Instructor Routes All Point to Wrong Path', 'HIGH',
         'template/src/feature-module/router/all_routes.tsx — Lines 42-47',
         '1. Log in as INSTRUCTOR\n2. Navigate to any of: instructor wishlist, reviews, quiz attempts, orders, chat, or referral pages\n3. All redirect to /instructor/instructor-withdraw',
         'Each route should navigate to its dedicated page',
         'instructorWishlist, instructorReviews, instructorQuizAttempts, instructorOrders, instructorChat, instructorReferral are ALL mapped to /instructor/instructor-withdraw. Clicking any of these 6 menu items opens the withdraw/payout page.',
         'Assign each route a unique, correct path in all_routes.tsx. Verify corresponding component files exist or create them.'),

        ('BUG-010', 'Community Module: Backend Complete, Zero Frontend', 'HIGH',
         'template/src/feature-module/ — No community pages exist',
         '1. Inspect backend: 11 community endpoints exist (posts, comments, likes)\n2. Inspect frontend: no /community/* routes in router.link.tsx\n3. No community service connected to UI',
         'Community features should be accessible to authenticated users',
         'The entire community module (forum, posts, discussions) is fully implemented in the backend with 11 endpoints but has no frontend implementation. Users cannot access this feature.',
         'Implement community frontend pages: post listing, post detail, create post, comments. Wire to existing community.service.ts. Add routes to router.link.tsx.'),

        ('BUG-011', 'WebSocket Messaging Not Implemented Client-Side', 'HIGH',
         'template/src/.env and template/src/environment.tsx',
         '1. Check REACT_APP_WS_URL is defined\n2. Search codebase for WebSocket client implementation\n3. Find none exists',
         'Real-time messaging should connect via WebSocket after login',
         'WS_URL is configured in environment (ws://localhost:8080/ws), backend WebSocket is configured with STOMP, but there is no WebSocket client code anywhere in the frontend. The messaging UI exists but likely polls or does nothing.',
         'Implement STOMP WebSocket client using @stomp/stompjs or sockjs-client. Connect on user login, subscribe to personal message channels.'),

        ('BUG-012', 'Admin Analytics Pages Defined but Not Routed', 'HIGH',
         'template/src/feature-module/router/all_routes.tsx and router.link.tsx',
         '1. Define adminAnalytics, adminReports, adminSubscriptions routes in all_routes.tsx\n2. Check router.link.tsx — these routes are absent\n3. Navigating to these URLs returns 404',
         'Admin analytics, reports, and subscriptions pages should be accessible',
         'Routes adminSubscriptions, adminAnalytics, adminReports exist in all_routes.tsx but are NOT imported or rendered in router.link.tsx. Backend endpoints for analytics exist (/admin/analytics) but are unreachable from frontend.',
         'Add the missing route entries to router.link.tsx with their corresponding component imports.'),

        ('BUG-013', 'Console.log Statements Throughout Production Code', 'MEDIUM',
         'template/src/services/api/axios.config.ts, course.service.ts, admin.service.ts, add-newCourse.tsx',
         '1. Open browser DevTools console\n2. Perform any API call (login, load courses, submit form)\n3. Observe API responses logged in plain text',
         'No console output in production — API responses may contain PII',
         'API responses (including user data, tokens, course details) are logged to console in production build. This exposes sensitive data in browser devtools.',
         'Remove all console.log/debug statements. Use a proper logging library (e.g., loglevel) with WARN/ERROR level in production. Add ESLint rule: no-console.'),

        ('BUG-014', 'TypeScript Unsafe any Cast in RoleGuard', 'MEDIUM',
         'template/src/feature-module/common/RoleGuard.tsx — Line 19',
         '1. Read RoleGuard.tsx\n2. Observe: user.role as any\n3. Type safety for authorization guard bypassed',
         'RoleGuard should use strongly-typed UserRole enum for comparisons',
         'Using as any in the authorization guard can mask type mismatches between UserRole enum values and comparison strings, potentially causing authorization bypass in edge cases.',
         'Import UserRole enum. Replace as any with proper typed comparison: (user.role as UserRole) === UserRole.ADMIN, or use type guards.'),

        ('BUG-015', 'Build Artifacts Committed to Git Repository', 'MEDIUM',
         'template/build/, template/build_output.txt, template/build_output2.txt, template/ts_errors.txt',
         '1. Run git status\n2. Observe: build/ directory, build_output files, ts_errors.txt (272KB) committed',
         'Build artifacts should be in .gitignore — only source code committed',
         '272KB ts_errors.txt and full /build directory are committed. This pollutes the repository, inflates clone size, and may expose internal type errors.',
         'Add build/, *.txt (build artifacts), build_output*.txt to .gitignore. Run: git rm -r --cached build/ build_output*.txt ts_errors.txt tmp_update_routes.js. Commit the .gitignore changes.'),

        ('BUG-016', 'Assignment Submission Flow Missing', 'MEDIUM',
         'academy-backend/.../controller/AssignmentController.java and frontend instructor-assignment page',
         '1. Create an assignment as instructor\n2. Attempt to submit as student\n3. No student submission endpoint exists',
         'Students should be able to submit and receive grades for assignments',
         'The Assignment entity and CRUD endpoints exist for instructors, but there are no student submission endpoints, no submission entity, and no grading flow. Assignments are essentially read-only for students.',
         'Add StudentAssignmentSubmission entity, repository, and endpoints: POST /student/assignments/{id}/submit, GET /student/assignments/{id}/submission. Add grading endpoint for instructors.'),

        ('BUG-017', 'Missing Route Slash: pages/contact-us', 'LOW',
         'template/src/feature-module/router/all_routes.tsx — contactUs route definition',
         '1. Check all_routes.tsx contactUs value\n2. Observe: "pages/contact-us" (missing leading /)\n3. Navigation to contact page produces unexpected behavior',
         'Route should be "/pages/contact-us" with leading slash',
         'Route is defined as "pages/contact-us" instead of "/pages/contact-us". This causes relative path resolution issues when navigating from nested routes.',
         'Add leading slash: contactUs: \'/pages/contact-us\''),

        ('BUG-018', 'Subscription Access Guard Incomplete', 'MEDIUM',
         'template/src/ — SubscriptionGuard or premium access logic',
         '1. Enroll in a premium course without active subscription\n2. Attempt to access premium lesson video',
         'Premium course content should be blocked without active subscription or payment',
         'Backend has subscription status checks, but frontend SubscriptionGuard only checks authentication, not actual subscription validity. Premium content may be accessible without payment.',
         'Enhance access guard: check user.subscription.status === ACTIVE or course.enrollmentType === PAID before allowing lesson access. Backend already enforces this but frontend should provide proper UX feedback.'),

        ('BUG-019', 'Multiple Home Page Variants Only One Active', 'LOW',
         'template/src/feature-module/HomePages/ — home-one through home-six',
         '1. Navigate to /\n2. homeone is rendered\n3. home-two through home-six are unreachable without route changes',
         'Only one home page variant should exist, or a switcher should be provided',
         'Six distinct home page implementations exist (homeone–homeSix). Only homeone is routed. The other five are dead code occupying approximately 600 lines each. This creates maintenance overhead.',
         'Remove home-two through home-six if they are not needed. If A/B testing, use a proper feature flag system.'),

        ('BUG-020', 'tmp_update_routes.js Temporary Script in Repository', 'LOW',
         'template/tmp_update_routes.js',
         '1. View repository root\n2. Observe tmp_update_routes.js — a temporary development script',
         'No temporary scripts should exist in the repository',
         'A temporary JavaScript file used during development is committed to the repository. This suggests sloppy git hygiene and may contain executable code.',
         'Delete the file: git rm tmp_update_routes.js. Update .gitignore to exclude tmp_*.js patterns.'),
    ]

    for bug in bugs:
        story.append(bug_card(*bug, styles))

    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # SECTION 5 — BACKEND CONNECTIVITY REPORT
    # ═══════════════════════════════════════════════════════════════════════════
    story.append(section_header('5. BACKEND CONNECTIVITY REPORT', '🔗', DARK_BG, styles))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        'This section maps each frontend service call to its corresponding backend endpoint, '
        'identifying connection status, mismatches, and missing integrations.',
        styles['body']))
    story.append(Spacer(1, 6))

    conn_data = [
        [Paragraph('<b>Frontend Call</b>', styles['table_header']),
         Paragraph('<b>Backend Endpoint</b>', styles['table_header']),
         Paragraph('<b>Status</b>', styles['table_header']),
         Paragraph('<b>Notes</b>', styles['table_header'])],

        # AUTH
        ('authService.login()', 'POST /api/v1/auth/login', '✅ Connected', 'Returns access+refresh tokens'),
        ('authService.register()', 'POST /api/v1/auth/register', '✅ Connected', 'Email verification sent'),
        ('authService.logout()', 'POST /api/v1/auth/logout', '✅ Connected', 'Revokes refresh token'),
        ('authService.forgotPassword()', 'POST /api/v1/auth/forgot-password', '✅ Connected', 'Reset email sent'),
        ('authService.resetPassword()', 'POST /api/v1/auth/reset-password', '✅ Connected', 'Password updated'),

        # COURSES
        ('courseService.getCourses()', 'GET /api/v1/courses', '✅ Connected', 'Paginated, filterable'),
        ('courseService.enrollInCourse()', 'POST /api/v1/courses/{id}/enroll', '✅ Connected', 'Checks payment/subscription'),
        ('courseService.getMyEnrolledCourses()', 'GET /api/v1/courses/my-courses', '✅ Connected', 'Returns enrollment list'),
        ('courseService.addToWishlist()', 'POST /api/v1/courses/{id}/wishlist', '✅ Connected', 'Unique constraint protected'),
        ('courseService.getCategories()', 'GET /api/v1/categories', '✅ Connected', 'Console.log present'),

        # INSTRUCTOR
        ('instructorService.getDashboard()', 'GET /api/v1/instructor/dashboard', '✅ Connected', 'KPIs returned'),
        ('instructorService.createCourse()', 'POST /api/v1/instructor/courses', '✅ Connected', 'Slug auto-generated'),
        ('instructorService.uploadLessonVideo()', 'POST /api/v1/instructor/lessons/{id}/upload-video', '✅ Connected', 'Creates Mux upload URL'),
        ('instructorService.requestPayout()', 'POST /api/v1/instructor/payouts/request', '✅ Connected', 'Bank details captured'),
        ('instructorService.getEarnings()', 'GET /api/v1/instructor/earnings', '✅ Connected', 'Paginated earnings'),

        # ADMIN
        ('adminService.getUsers()', 'GET /api/v1/admin/users', '✅ Connected', 'Paginated + searchable'),
        ('adminService.banUser()', 'POST /api/v1/admin/users/{id}/ban', '✅ Connected', 'Reason captured'),
        ('adminService.approveCourse()', 'POST /api/v1/admin/courses/{id}/approve', '✅ Connected', 'Updates course status'),
        ('adminService.getTransactions()', 'GET /api/v1/admin/transactions', '✅ Connected', 'Full transaction history'),
        ('adminService.getAnalytics()', 'GET /api/v1/admin/analytics', '❌ NOT CONNECTED', 'Route missing from router.link.tsx — endpoint exists but unreachable'),
        ('adminService.getReports()', 'GET /api/v1/admin/reports', '❌ NOT CONNECTED', 'Route missing from router.link.tsx'),

        # PAYMENTS
        ('paymentService.purchaseCourse()', 'POST /api/v1/payments/course/{id}', '✅ Connected', 'Returns PayZone payment URL'),
        ('paymentService.getPaymentHistory()', 'GET /api/v1/payments/history', '✅ Connected', 'Transaction list'),

        # NOT CONNECTED
        ('N/A — No frontend', 'GET /api/v1/community/posts', '🔌 NOT CONNECTED', 'Community module has no frontend pages'),
        ('N/A — No frontend', 'POST /api/v1/community/posts', '🔌 NOT CONNECTED', 'No create post UI'),
        ('N/A — No WebSocket client', 'WebSocket /ws/chat', '🔌 NOT CONNECTED', 'STOMP server configured, no JS client'),
        ('N/A — No frontend', 'GET /api/v1/subscriptions/my-subscription', '⚠️ Partial', 'Subscription UI incomplete'),
    ]

    conn_rows = [conn_data[0]]
    for fe, be, status, note in conn_data[1:]:
        status_color = STATUS_OK if '✅' in status else (STATUS_CRIT if '❌' in status else (ACCENT_GRAY if '🔌' in status else STATUS_HIGH))
        st_s = ParagraphStyle('_cs', fontName='Helvetica-Bold', fontSize=7.5, textColor=status_color)
        conn_rows.append([
            Paragraph(fe, styles['table_cell_small']),
            Paragraph(be, styles['code']),
            Paragraph(status, st_s),
            Paragraph(note, styles['table_cell_small']),
        ])
    conn_t = Table(conn_rows, colWidths=[42*mm, 52*mm, 30*mm, 54*mm], repeatRows=1)
    conn_t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), ACCENT_BLUE),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ('GRID', (0, 0), (-1, -1), 0.3, BORDER_LIGHT),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(conn_t)
    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # SECTION 6 — UI/UX ISSUES
    # ═══════════════════════════════════════════════════════════════════════════
    story.append(section_header('6. UI/UX ISSUES', '🎨', DARK_BG, styles))
    story.append(Spacer(1, 8))

    ux_issues = [
        ('Multiple Home Page Variants (6)', 'HIGH',
         'Six home page implementations exist (homeone–homeSix). Only homeone is routed. The dead code creates confusion and maintenance overhead. Users never see the other 5 designs.'),
        ('Instructor Dashboard: 6 Broken Navigation Links', 'CRITICAL',
         'Instructor sidebar links for Wishlist, Reviews, Quiz Attempts, Orders, Chat, and Referral all navigate to the Payout/Withdraw page. Users are confused when clicking these menu items.'),
        ('Admin Section Missing Pages', 'HIGH',
         'Admin Analytics, Admin Reports, and Admin Subscriptions menu items are present in the UI but navigate to a blank/404 page since the routes are not wired in the router.'),
        ('No Error Boundary Components', 'MEDIUM',
         'No React error boundaries are implemented. Any uncaught JavaScript error in a component will crash the entire application rather than showing a graceful error message.'),
        ('Community Feature Invisible to Users', 'HIGH',
         'The community/forum feature is fully built on the backend but completely invisible in the UI. There is no navigation link, no page, and no way for users to discover or use it.'),
        ('Real-time Messaging UI Without Real-time', 'HIGH',
         'The messaging UI pages exist for both students and instructors, but without a WebSocket client, messages either require manual refresh or do not update in real-time.'),
        ('Subscription Management UX Incomplete', 'MEDIUM',
         'Users can initiate a subscription but cannot view their current plan details, manage billing, or see clear next-billing-date information in a dedicated UI.'),
        ('Assignment Feature: Student View Missing', 'MEDIUM',
         'Instructors can create assignments but students have no UI to view, submit, or receive grades for assignments. The feature is half-implemented from a user journey perspective.'),
        ('Cart/Checkout Error States Not Handled', 'MEDIUM',
         'When a payment fails or PayZone returns an error, the checkout page does not show a meaningful error message. Users are left in an unclear state.'),
        ('Console Logs Visible in DevTools', 'LOW',
         'API responses including user data, course details, and auth tokens are logged to the browser console in production, exposing sensitive data to tech-savvy users.'),
        ('Inconsistent Loading States', 'LOW',
         'Some pages show loading spinners while data fetches, others show blank screens. No unified skeleton-loading pattern across the application.'),
        ('Blog Pages: Static Template Only', 'LOW',
         '8 blog layout variants exist as static templates with no backend connection. No blog API endpoints exist. Blog links in navigation lead to dummy content.'),
    ]

    for issue, severity, desc in ux_issues:
        sev_color = STATUS_CRIT if severity == 'CRITICAL' else (STATUS_HIGH if severity == 'HIGH' else (STATUS_MED if severity == 'MEDIUM' else STATUS_LOW))
        row = [[
            Paragraph(f'<b>{issue}</b>', ParagraphStyle('_ui', fontName='Helvetica-Bold',
                       fontSize=9, textColor=TEXT_DARK)),
            Paragraph(severity, ParagraphStyle('_us', fontName='Helvetica-Bold',
                       fontSize=8, textColor=sev_color, alignment=TA_CENTER)),
            Paragraph(desc, styles['body_small']),
        ]]
        t = Table(row, colWidths=[55*mm, 18*mm, 105*mm])
        t.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.3, BORDER_LIGHT),
            ('ROWBACKGROUNDS', (0, 0), (-1, -1), [LIGHT_BG]),
            ('TOPPADDING', (0, 0), (-1, -1), 7),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('ALIGN', (1, 0), (1, -1), 'CENTER'),
            ('LINEBELOW', (0, 0), (-1, -1), 0.4, BORDER_LIGHT),
        ]))
        story.append(t)
        story.append(Spacer(1, 3))

    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # SECTION 7 — PERFORMANCE ANALYSIS
    # ═══════════════════════════════════════════════════════════════════════════
    story.append(section_header('7. PERFORMANCE ANALYSIS', '⚡', DARK_BG, styles))
    story.append(Spacer(1, 8))

    perf_issues = [
        ('Bundle Size: 45+ Production Dependencies', 'MEDIUM',
         'The frontend includes Ant Design (5.x), Bootstrap, PrimeReact, Swiper, React Slick, and multiple icon sets simultaneously. This creates a very large initial JavaScript bundle affecting Time to Interactive (TTI).',
         'Implement code splitting per route. Use tree-shaking aggressively. Replace multiple UI libraries with a single consistent one. Target bundle <500KB gzipped.'),
        ('Six Unused Home Page Variants', 'LOW',
         'Five of six home page implementations are never rendered but are still included in the bundle. Each contains Swiper carousels, animation libraries, and multiple components.',
         'Delete unused home page variants. The dead code wastes compile time and bundle space.'),
        ('No React.memo or useMemo on Heavy Components', 'MEDIUM',
         'Dashboard components re-render on every Redux state change. Course listing cards, charts (ApexCharts), and sidebar components likely re-render unnecessarily.',
         'Wrap stable components with React.memo. Memoize expensive selectors with useMemo/reselect. Profile with React DevTools Profiler.'),
        ('Synchronous Axios Config: Console Logs on Every Request', 'LOW',
         'Every API request logs to console via the interceptor. This is synchronous I/O on the critical request path.',
         'Remove all console.log calls from the axios interceptor.'),
        ('HikariCP: 10-Connection Pool May Be Insufficient', 'MEDIUM',
         'maximum-pool-size: 10 with minimum-idle: 5. For a platform expecting concurrent students watching videos and submitting quizzes, 10 connections may cause queuing under load.',
         'Monitor pool utilization in production. Consider increasing to 20-30 based on DB server capacity. Enable HikariCP metrics via Actuator.'),
        ('Hibernate show-sql: true in Non-Production Logs', 'LOW',
         'show-sql: false is set, but logging.level.org.hibernate.SQL: DEBUG is enabled — this logs all SQL to the console in DEBUG mode, creating I/O overhead.',
         'Set org.hibernate.SQL to INFO or WARN in production profile. Only enable SQL logging in development.'),
        ('No Caching Layer for Public Course Data', 'MEDIUM',
         'GET /courses, /courses/popular, /categories — these are called on every page load by every user with no caching. Under load, this hits the database on every request.',
         'Add Spring Cache (@Cacheable) on popular course and category queries. Use Redis or Caffeine as backing store. TTL of 60-300 seconds for public data.'),
        ('Video Loading: No CDN or Pre-signed URL Caching', 'MEDIUM',
         'Mux signed URLs (1-hour expiry) are fetched per lesson view. No client-side caching of recently obtained URLs. Each video start triggers an API call.',
         'Cache signed URLs in React state or localStorage with expiry. Implement prefetching for next lesson URL while watching current lesson.'),
    ]

    for title, sev, problem, fix in perf_issues:
        sev_color = STATUS_HIGH if sev == 'HIGH' else (STATUS_MED if sev == 'MEDIUM' else STATUS_LOW)
        lbl_s = ParagraphStyle('_pl', fontName='Helvetica-Bold', fontSize=8, textColor=ACCENT_BLUE)
        val_s = ParagraphStyle('_pv', fontName='Helvetica', fontSize=8.5, textColor=TEXT_DARK, leading=13)
        rows = [
            [[Paragraph(f'<b>{title}</b>', ParagraphStyle('_pt', fontName='Helvetica-Bold', fontSize=9.5,
              textColor=TEXT_DARK)), Paragraph(sev, ParagraphStyle('_ps', fontName='Helvetica-Bold',
              fontSize=8, textColor=sev_color, alignment=TA_RIGHT))]],
            [[Paragraph('Problem', lbl_s), Paragraph(problem, val_s)]],
            [[Paragraph('Suggested Fix', lbl_s), Paragraph(fix, val_s)]],
        ]
        hdr = Table([[Paragraph(f'<b>{title}</b>', ParagraphStyle('_pt2', fontName='Helvetica-Bold',
                      fontSize=9.5, textColor=TEXT_DARK)),
                      Paragraph(sev, ParagraphStyle('_ps2', fontName='Helvetica-Bold', fontSize=8,
                      textColor=sev_color, alignment=TA_RIGHT))]], colWidths=[140*mm, 38*mm])
        hdr.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#EBF4FF')),
            ('TOPPADDING', (0, 0), (-1, -1), 7), ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
            ('LEFTPADDING', (0, 0), (-1, -1), 8), ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ]))
        body_rows = [
            [Paragraph('Problem', lbl_s), Paragraph(problem, val_s)],
            [Paragraph('Fix', lbl_s), Paragraph(fix, val_s)],
        ]
        body_t = Table(body_rows, colWidths=[20*mm, 158*mm])
        body_t.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.3, BORDER_LIGHT),
            ('TOPPADDING', (0, 0), (-1, -1), 6), ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 8), ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#F8F9FA')),
        ]))
        story.append(KeepTogether([hdr, body_t, Spacer(1, 8)]))

    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # SECTION 8 — SECURITY RISK ASSESSMENT
    # ═══════════════════════════════════════════════════════════════════════════
    story.append(section_header('8. SECURITY RISK ASSESSMENT', '🔒', DARK_BG, styles))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        'Security assessment based on OWASP Top 10 (2021) and general web application security best practices. '
        'Eight critical vulnerabilities require immediate remediation before any production deployment.',
        styles['body']))
    story.append(Spacer(1, 8))

    security_data = [
        ('Gmail App Password in Source Code',
         'application.yml (MAIL_PASSWORD default)',
         'CRITICAL',
         'Revoke immediately. Remove default. Store only in vault/env variable.'),
        ('JWT Secret Key in Source Control',
         'application.yml (JWT_SECRET default)',
         'CRITICAL',
         'Rotate secret. Remove default value. Invalidate all existing sessions.'),
        ('CORS: Wildcard + Credentials=True',
         'SecurityConfig.java — corsConfig',
         'CRITICAL',
         'Replace * with explicit trusted origins list.'),
        ('Spring Actuator Publicly Accessible',
         'SecurityConfig.java — /actuator/**',
         'CRITICAL',
         'Require ADMIN role for all actuator endpoints.'),
        ('Unauthenticated Admin Registration Endpoint',
         'AuthController — /auth/register-admin',
         'CRITICAL',
         'Add @PreAuthorize(\'ADMIN\') or remove the endpoint entirely.'),
        ('Known Admin Password in DB Migration',
         'V2__quiz_tables.sql — Admin@1234',
         'CRITICAL',
         'Remove seeded password. Force password change on first login.'),
        ('Database Default Password "0000"',
         'application.yml (DB_PASSWORD default)',
         'CRITICAL',
         'Remove default. Fail startup if DB_PASSWORD not set.'),
        ('Mux API Key in .env Committed to Git',
         'template/.env',
         'CRITICAL',
         'Add .env to .gitignore. Rotate key. Use .env.example.'),
        ('JWT Stored in localStorage (XSS Risk)',
         'auth.service.ts — localStorage.getItem(ACCESS_TOKEN_KEY)',
         'HIGH',
         'Consider HttpOnly cookies for token storage. Add CSP headers.'),
        ('No Rate Limiting on Auth Endpoints',
         '/auth/login, /auth/register, /auth/forgot-password',
         'HIGH',
         'Add Spring Boot rate limiting (Bucket4j or custom filter) on auth routes.'),
        ('No Input Validation on Course/Profile Fields',
         'Backend controllers — missing @Valid annotations on some endpoints',
         'HIGH',
         'Add @Valid + Bean Validation (javax.validation) to all request DTOs.'),
        ('Public Webhook Endpoints Without IP Filtering',
         '/payments/webhook, /subscriptions/webhook',
         'MEDIUM',
         'In addition to signature verification, whitelist PayZone IP ranges.'),
        ('Sensitive Data in Console Logs',
         'axios.config.ts, admin.service.ts',
         'MEDIUM',
         'Remove all console.log statements. Implement server-side audit logging.'),
        ('IDOR: No Ownership Validation in Some Endpoints',
         'InstructorController — course/module/lesson endpoints',
         'HIGH',
         'Verify authenticated instructor owns the course before modifying modules/lessons. Check service implementations for ownership validation.'),
        ('Swagger UI Publicly Accessible',
         'SecurityConfig — /swagger-ui/**, /v3/api-docs/**',
         'MEDIUM',
         'Disable Swagger in production (springdoc.swagger-ui.enabled: false). Or require ADMIN role.'),
    ]

    story.append(make_security_table(security_data, styles))
    story.append(Spacer(1, 10))

    story.append(Paragraph('OWASP Top 10 Mapping:', styles['subsection']))
    owasp_map = [
        ('A01 — Broken Access Control', 'MEDIUM', 'Potential IDOR in instructor endpoints; admin registration endpoint unprotected'),
        ('A02 — Cryptographic Failures', 'CRITICAL', 'JWT secret + Gmail password in plaintext source code'),
        ('A03 — Injection', 'LOW', 'Spring Data JPA parameterized queries prevent SQL injection'),
        ('A04 — Insecure Design', 'HIGH', 'Admin seeded with known credentials; no rate limiting design'),
        ('A05 — Security Misconfiguration', 'CRITICAL', 'Actuator public; CORS wildcard+credentials; Swagger UI public'),
        ('A06 — Vulnerable Components', 'LOW', 'Dependencies current as of audit date; monitor for CVEs'),
        ('A07 — Auth & Session Failures', 'HIGH', 'JWT in localStorage vulnerable to XSS; no rate limiting on login'),
        ('A08 — Software Integrity', 'LOW', 'No SBOM or integrity checks; package-lock.json committed'),
        ('A09 — Logging Failures', 'MEDIUM', 'Sensitive data logged to console; no centralized audit log'),
        ('A10 — SSRF', 'LOW', 'External API calls to Mux/PayZone use configured base URLs; low risk'),
    ]
    ow_rows = [[Paragraph('<b>OWASP Category</b>', styles['table_header']),
                Paragraph('<b>Risk Level</b>', styles['table_header']),
                Paragraph('<b>Finding</b>', styles['table_header'])]]
    for cat, risk, finding in owasp_map:
        rc = {'CRITICAL': STATUS_CRIT, 'HIGH': STATUS_HIGH, 'MEDIUM': STATUS_MED, 'LOW': STATUS_LOW}.get(risk, TEXT_GRAY)
        ow_rows.append([
            Paragraph(cat, styles['table_cell_small']),
            Paragraph(risk, ParagraphStyle('_or', fontName='Helvetica-Bold', fontSize=7.5,
                       textColor=rc, alignment=TA_CENTER)),
            Paragraph(finding, styles['table_cell_small']),
        ])
    ow_t = Table(ow_rows, colWidths=[52*mm, 22*mm, 104*mm], repeatRows=1)
    ow_t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), STATUS_CRIT),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#FFF5F5')]),
        ('GRID', (0, 0), (-1, -1), 0.3, BORDER_LIGHT),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (1, 0), (1, -1), 'CENTER'),
    ]))
    story.append(ow_t)
    story.append(PageBreak())

    # ═══════════════════════════════════════════════════════════════════════════
    # SECTION 9 — RECOMMENDATIONS & FIX PRIORITY PLAN
    # ═══════════════════════════════════════════════════════════════════════════
    story.append(section_header('9. RECOMMENDATIONS & FIX PRIORITY PLAN', '🗺️', DARK_BG, styles))
    story.append(Spacer(1, 8))
    story.append(Paragraph(
        'Issues are organized into three sprints. Critical security issues must be resolved before any production deployment. '
        'Feature completeness and UX improvements follow in subsequent sprints.',
        styles['body']))
    story.append(Spacer(1, 8))

    sprints = [
        ('SPRINT 0 — IMMEDIATE (Before Production)', STATUS_CRIT, [
            ('SEC-1', 'CRITICAL', 'Revoke Gmail app password; remove hardcoded MAIL_PASSWORD default from application.yml', '1 hour'),
            ('SEC-2', 'CRITICAL', 'Rotate JWT secret; remove hardcoded JWT_SECRET default; invalidate all sessions', '1 hour'),
            ('SEC-3', 'CRITICAL', 'Fix CORS: replace allowedOriginPatterns("*") with explicit trusted origins', '30 min'),
            ('SEC-4', 'CRITICAL', 'Restrict /actuator/** to ADMIN role in SecurityConfig', '15 min'),
            ('SEC-5', 'CRITICAL', 'Add @PreAuthorize("hasRole(\'ADMIN\')") to /register-admin or delete the endpoint', '15 min'),
            ('SEC-6', 'CRITICAL', 'Remove seeded admin password from V2 migration; add first-login password change', '2 hours'),
            ('SEC-7', 'CRITICAL', 'Remove DB_PASSWORD default "0000"; add startup validation', '15 min'),
            ('SEC-8', 'CRITICAL', 'Add template/.env to .gitignore; rotate Mux env key', '30 min'),
            ('GIT-1', 'HIGH', 'Remove build/, build_output*.txt, ts_errors.txt, tmp_update_routes.js from git', '30 min'),
        ]),
        ('SPRINT 1 — HIGH PRIORITY (Week 1–2)', STATUS_HIGH, [
            ('FE-1', 'HIGH', 'Fix 6 duplicate instructor routes in all_routes.tsx pointing to instructor-withdraw', '1 hour'),
            ('FE-2', 'HIGH', 'Wire admin analytics, reports, subscriptions routes in router.link.tsx', '2 hours'),
            ('FE-3', 'HIGH', 'Remove all console.log statements from production code (axios interceptor, services, forms)', '3 hours'),
            ('FE-4', 'HIGH', 'Fix missing leading slash: contactUs route in all_routes.tsx', '15 min'),
            ('FE-5', 'HIGH', 'Implement React error boundary components for graceful error handling', '4 hours'),
            ('BE-1', 'HIGH', 'Add rate limiting on /auth/login, /auth/register, /auth/forgot-password (Bucket4j)', '4 hours'),
            ('BE-2', 'HIGH', 'Disable Swagger UI in production profile (springdoc.swagger-ui.enabled: false)', '15 min'),
            ('BE-3', 'HIGH', 'Verify ownership validation in InstructorController for all course/module/lesson mutations', '4 hours'),
            ('FE-6', 'HIGH', 'Fix TypeScript as any cast in RoleGuard.tsx — use typed UserRole enum', '1 hour'),
        ]),
        ('SPRINT 2 — FEATURE COMPLETION (Week 3–4)', STATUS_MED, [
            ('FEAT-1', 'HIGH', 'Implement Community frontend: post list, post detail, create post, comments', '3 days'),
            ('FEAT-2', 'HIGH', 'Implement WebSocket client (STOMP/sockjs) for real-time messaging', '2 days'),
            ('FEAT-3', 'HIGH', 'Complete subscription management UI: current plan, billing date, cancel flow', '1 day'),
            ('FEAT-4', 'MEDIUM', 'Implement student assignment submission flow + instructor grading UI', '2 days'),
            ('FEAT-5', 'MEDIUM', 'Improve cart/checkout error handling with PayZone failure states', '1 day'),
            ('FEAT-6', 'MEDIUM', 'Complete video upload UX: remove console.logs, add proper error states, upload progress', '1 day'),
            ('FE-7', 'MEDIUM', 'Remove 5 unused home page variants (home-two through home-six)', '2 hours'),
            ('FE-8', 'MEDIUM', 'Add unified skeleton-loading pattern across all data-fetch pages', '1 day'),
        ]),
        ('SPRINT 3 — PERFORMANCE & POLISH (Week 5–6)', STATUS_LOW, [
            ('PERF-1', 'MEDIUM', 'Implement route-based code splitting to reduce initial bundle size', '1 day'),
            ('PERF-2', 'MEDIUM', 'Consolidate UI libraries: pick one primary (Ant Design or Bootstrap, not both)', '2 days'),
            ('PERF-3', 'MEDIUM', 'Add Spring Cache (@Cacheable) on public course/category queries with Redis/Caffeine', '1 day'),
            ('PERF-4', 'MEDIUM', 'Add React.memo to stable components (CourseCard, Sidebar, DashboardStat)', '1 day'),
            ('PERF-5', 'LOW', 'Increase HikariCP pool size based on production load testing results', '2 hours'),
            ('PERF-6', 'LOW', 'Cache Mux signed URLs client-side to avoid re-fetching on each lesson load', '4 hours'),
            ('SEC-9', 'MEDIUM', 'Migrate JWT from localStorage to HttpOnly cookies to mitigate XSS token theft', '2 days'),
            ('SEC-10', 'LOW', 'Add PayZone IP allowlist in addition to signature verification on webhook endpoints', '4 hours'),
        ]),
    ]

    for sprint_title, sprint_color, tasks in sprints:
        story.append(Spacer(1, 6))
        hdr_data = [[Paragraph(f'<b>{sprint_title}</b>',
                     ParagraphStyle('_sh', fontName='Helvetica-Bold', fontSize=11, textColor=colors.white))]]
        sprint_hdr = Table(hdr_data, colWidths=[PAGE_W - 30*mm])
        sprint_hdr.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), sprint_color),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ]))
        story.append(sprint_hdr)

        task_rows = [[Paragraph('<b>ID</b>', styles['table_header']),
                      Paragraph('<b>Priority</b>', styles['table_header']),
                      Paragraph('<b>Task</b>', styles['table_header']),
                      Paragraph('<b>Effort</b>', styles['table_header'])]]
        for tid, pri, task, effort in tasks:
            p_color = STATUS_CRIT if pri == 'CRITICAL' else (STATUS_HIGH if pri == 'HIGH' else (STATUS_MED if pri == 'MEDIUM' else STATUS_LOW))
            task_rows.append([
                Paragraph(f'<b>{tid}</b>', ParagraphStyle('_tid', fontName='Helvetica-Bold',
                           fontSize=8, textColor=ACCENT_BLUE)),
                Paragraph(pri, ParagraphStyle('_tpri', fontName='Helvetica-Bold', fontSize=7.5,
                           textColor=p_color, alignment=TA_CENTER)),
                Paragraph(task, styles['table_cell_small']),
                Paragraph(effort, ParagraphStyle('_tef', fontName='Helvetica', fontSize=7.5,
                           textColor=TEXT_GRAY, alignment=TA_CENTER)),
            ])
        task_t = Table(task_rows, colWidths=[15*mm, 20*mm, 120*mm, 23*mm], repeatRows=1)
        task_t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ACCENT_BLUE),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
            ('GRID', (0, 0), (-1, -1), 0.3, BORDER_LIGHT),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ALIGN', (1, 0), (1, -1), 'CENTER'),
            ('ALIGN', (3, 0), (3, -1), 'CENTER'),
        ]))
        story.append(task_t)

    story.append(Spacer(1, 12))
    story.append(divider(styles))

    # Final note
    final_note = Table([[Paragraph(
        '<b>Final Note:</b> The Cake Design Academy platform has a strong architectural foundation with comprehensive '
        'backend coverage and a well-organized frontend. The core learning flow (browse → enroll → watch → quiz → certificate) '
        'is functional end-to-end. The primary concerns are: (1) security secrets in source code requiring immediate rotation, '
        '(2) several significant features built on the backend but missing frontend implementations, '
        'and (3) routing bugs that break navigation for instructors. With the Sprint 0 and Sprint 1 fixes applied, '
        'the platform would be ready for a secure beta deployment. Full production readiness requires Sprint 2 completion.',
        styles['body'])]],
        colWidths=[PAGE_W - 30*mm])
    final_note.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#EBF4FF')),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('LEFTPADDING', (0, 0), (-1, -1), 14),
        ('RIGHTPADDING', (0, 0), (-1, -1), 14),
        ('LINEBEFOREE', (0, 0), (0, -1), 4, ACCENT_BLUE),
    ]))
    story.append(final_note)

    # BUILD
    doc.build(story, canvasmaker=HeaderFooterCanvas)
    print(f'Report generated: {output_path}')


if __name__ == '__main__':
    output = r'C:\Users\asus\Documents\Project main\plateforme\Cake_Design_Academy_Audit_Report.pdf'
    build_report(output)
