package com.academy.controller;

import com.academy.dto.response.ApiResponse;
import com.academy.exception.BadRequestException;
import com.academy.exception.ForbiddenException;
import com.academy.repository.VideoAssetRepository;
import com.academy.security.UserPrincipal;
import com.academy.service.LessonService;
import com.academy.service.VideoStorageService;
import com.academy.service.VideoTokenService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.servlet.http.HttpServletRequest;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.io.InputStreamResource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.UUID;

@Slf4j
@RestController
@RequestMapping("/api/v1/videos")
@RequiredArgsConstructor
@Tag(name = "Video Streaming", description = "Self-hosted video upload and HTTP Range streaming")
public class VideoStreamingController {

    private final VideoStorageService  videoStorageService;
    private final VideoTokenService    videoTokenService;
    private final LessonService        lessonService;
    private final VideoAssetRepository videoAssetRepository;

    /** Default chunk size served per Range request: 10 MB. */
    private static final long DEFAULT_CHUNK = 10L * 1024 * 1024;

    // ─────────────────────────────────────────────────────────────────────────
    // Upload
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Upload (or replace) the video file for a lesson.
     * <p>
     * The file is streamed directly to disk via {@link VideoStorageService};
     * no DB transaction is held open during the file copy.  The subsequent
     * metadata write is handled atomically inside
     * {@link LessonService#registerLocalVideo}.
     */
    @PostMapping(value = "/{lessonId}/upload", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    @PreAuthorize("hasAnyRole('INSTRUCTOR', 'ADMIN')")
    @Operation(summary = "Upload a video file for a lesson (multipart, up to 4 GB)")
    public ResponseEntity<ApiResponse<Void>> uploadVideo(
            @PathVariable UUID lessonId,
            @RequestParam("video") MultipartFile videoFile,
            @AuthenticationPrincipal UserPrincipal principal) throws IOException {

        // Validate file
        if (videoFile == null || videoFile.isEmpty()) {
            throw new BadRequestException("Video file is required");
        }
        String contentType = videoFile.getContentType();
        if (contentType == null || !contentType.startsWith("video/")) {
            throw new BadRequestException("Only video files are accepted (video/*)");
        }

        // Ownership check — runs in its own read-only transaction inside the service
        lessonService.verifyInstructorCanModifyLesson(lessonId, principal.getId(), principal.getRole());

        // Stream the file to disk (long operation — no DB connection held)
        String filePath = videoStorageService.storeVideo(
                videoFile.getInputStream(),
                videoFile.getOriginalFilename(),
                videoFile.getSize()
        );

        // Persist metadata atomically (own @Transactional in LessonServiceImpl)
        lessonService.registerLocalVideo(
                lessonId,
                filePath,
                videoFile.getOriginalFilename(),
                contentType,
                videoFile.getSize()
        );

        log.info("Video uploaded for lesson {}: {}", lessonId, filePath);
        return ResponseEntity.ok(ApiResponse.success("Video uploaded successfully"));
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Stream  (HTTP Range)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Stream a lesson video using HTTP Range requests.
     * <p>
     * Access is controlled by a short-lived signed token (not by Spring Security),
     * so this endpoint is declared {@code permitAll} in SecurityConfig.
     * The token is generated by {@link LessonService#getVideoUrl}.
     */
    @GetMapping("/{lessonId}/stream")
    @Operation(summary = "Stream a video with HTTP 206 Partial Content support")
    public ResponseEntity<InputStreamResource> streamVideo(
            @PathVariable UUID lessonId,
            @RequestParam(required = false) String token,
            HttpServletRequest request) throws IOException {

        // Token validation
        if (!videoTokenService.validateToken(token, lessonId)) {
            return ResponseEntity.status(HttpStatus.FORBIDDEN).build();
        }

        // Resolve video asset
        var asset = videoAssetRepository.findByLessonId(lessonId)
                .orElseThrow(() -> new BadRequestException("No video found for this lesson"));

        if (!videoStorageService.videoExists(asset.getFilePath())) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
        }

        long totalSize = videoStorageService.getVideoSize(asset.getFilePath());

        // ── Parse Range header ────────────────────────────────────────────────
        String rangeHeader   = request.getHeader(HttpHeaders.RANGE);
        long   rangeStart    = 0;
        long   rangeEnd      = Math.min(totalSize - 1, DEFAULT_CHUNK - 1);
        boolean isRange      = false;

        if (rangeHeader != null && rangeHeader.startsWith("bytes=")) {
            isRange = true;
            String rangeValue = rangeHeader.substring(6);
            String[] parts    = rangeValue.split("-");
            rangeStart = Long.parseLong(parts[0].trim());
            if (parts.length > 1 && !parts[1].isBlank()) {
                rangeEnd = Long.parseLong(parts[1].trim());
            } else {
                rangeEnd = Math.min(totalSize - 1, rangeStart + DEFAULT_CHUNK - 1);
            }
            rangeEnd = Math.min(rangeEnd, totalSize - 1);
        }

        long contentLength = rangeEnd - rangeStart + 1;

        // ── Build response ────────────────────────────────────────────────────
        var stream = videoStorageService.streamVideo(asset.getFilePath(), rangeStart, rangeEnd);

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.parseMediaType(
                asset.getContentType() != null ? asset.getContentType() : "video/mp4"));
        headers.set(HttpHeaders.ACCEPT_RANGES,  "bytes");
        headers.set(HttpHeaders.CONTENT_RANGE,
                "bytes " + rangeStart + "-" + rangeEnd + "/" + totalSize);
        headers.setContentLength(contentLength);
        headers.set(HttpHeaders.CACHE_CONTROL, "no-cache, no-store");

        HttpStatus status = isRange ? HttpStatus.PARTIAL_CONTENT : HttpStatus.OK;

        return ResponseEntity.status(status)
                .headers(headers)
                .body(new InputStreamResource(stream));
    }
}
